# Generated by Django 3.0.5 on 2020-09-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200609_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('coordinates', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
